# Redis二级缓存配置
spring:
  cache:
    type: redis
    redis:
      # 缓存过期时间设置
      time-to-live: 3600000  # 默认1小时
      # 是否允许缓存空值
      cache-null-values: true
      # 缓存键前缀
      key-prefix: "turtle_soup:"
      # 使用二级缓存
      use-key-prefix: true

  redis:
    host: localhost
    port: 6379
    database: 0
    # 连接超时时间
    timeout: 10000
    # 连接池配置
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1

# 缓存配置
cache:
  # 一级缓存（本地缓存）配置
  local:
    # 初始容量
    initial-capacity: 100
    # 最大容量
    maximum-size: 1000
    # 过期时间（秒）
    expire-after-write: 300
  
  # 二级缓存（Redis）配置
  redis:
    # 故事模板缓存
    story-template:
      name: "story_template"
      ttl: 86400  # 24小时
    # 对话历史缓存
    dialog-history:
      name: "dialog_history"
      ttl: 3600   # 1小时
    # 用户会话缓存
    user-session:
      name: "user_session"
      ttl: 1800   # 30分钟